on: ["push", "pull_request"]

name: Test

jobs:
  find-templates:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.find-templates.outputs.templates }}
    steps:
    - uses: actions/checkout@v2
    - name: Find templates
      id: find-templates
      run: |
        TEMPLATES=${{ toJSON(`find tests -type f -exec basename {} .json \;`) }}
        echo ::set-output name=templates::${TEMPLATES}

  validate-template:
    needs:
    - find-templates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template: ${{ fromJSON(needs.find-templates.outputs.templates) }}
    steps:
    - uses: actions/checkout@v2
    - uses: ApeWorX/github-action@v1
    - run: ape plugins install -U template
    - run: ape template . --replay-file tests/${{ matrix.template }}.json
    - name: Install plugins
      run: |
        cd ${{ matrix.template }}
        ape plugins install -U .
    - name: Compile contracts
      run: |
        cd ${{ matrix.template }}
        ape compile --size
    - name: Run tests
      run: |
        cd ${{ matrix.template }}
        ape test -s
